### ISSUE TITLE
Sonos S2 - No status changes?

### ISSUE THREAD

**Issue by matthias-burgfried** [svrooij/sonos2mqtt#104]
Good evening. I updated my system to S2 yesterday and I ran into a problem. I can still control the system, but I can't get any more system changes via MQTT. 

```
# docker logs sonos2mqtt -f
2020-06-11T19:44:36.349Z [Information] Starting sonos2mqtt
2020-06-11T19:44:36.358Z [Information] LogLevel changed to information
2020-06-11T19:44:36.372Z [Information] Found 6 sonos speakers
2020-06-11T19:44:36.419Z [Information] Mqtt connection changed to connected: true
```

```
# mosquitto_sub -h 10.10.10.10 -v -t sonos/#
sonos/connected 2
```

docker-compose.yml
```
...
sonos2mqtt:
    image: svrooij/sonos2mqtt
    container_name: sonos2mqtt
    environment:
      - SONOS2MQTT_DEVICE=${SONOS1}
      - SONOS2MQTT_MQTT=mqtt://${MQTT}:1883
      - SONOS_LISTENER_HOST=${DOCKER_HOST}
      - TZ=Europe/Berlin
    depends_on:
      - mqtt
    restart: unless-stopped
...
```
My question: I' m using the Docker image, how can I turn on debug logging?

**Comment by matthias-burgfried** [comment]
My mistake. I have missed to expose the listening port.

docker-compose.yml
```
...
sonos2mqtt:
    image: svrooij/sonos2mqtt
    container_name: sonos2mqtt
    environment:
      - SONOS2MQTT_DEVICE=${SONOS1}
      - SONOS2MQTT_MQTT=mqtt://${MQTT}:1883
      - SONOS_LISTENER_HOST=${DOCKER_HOST}
      - TZ=Europe/Berlin
    depends_on:
      - mqtt
    restart: unless-stopped
    ports:
      - ${SONOS2MQTT_HOST}:6329:6329
...
```
