### ISSUE TITLE
EXPOSE port incorrect according to documentation

### ISSUE THREAD

**Issue by bramwalet** [svrooij/sonos2mqtt#60]
In all parts of the documentation the listen port is specified as 6329:
Examples:
> Run docker run --env-file .env -p 632**9**:632**9** svrooij/sonos2mqtt

and
> Docker-compose
``` 
version: "3.7"
 services:
  sonos:
    ...
    ports:
      - "6329:6329"
```
However, the Dockerfile exposes 632**6**, which is incorrect / inconsistent with the provided mappings and will not work. 

https://github.com/svrooij/sonos2mqtt/blob/32070c4b0e1ecdb8e8221afe580a5388e0b59db9/Dockerfile#L7
